require:
  - rubocop-rails

AllCops:
  NewCops: disable
  Exclude:
    - .git/**/*
    - bin/**/*
    - vendor/**/*
    - tmp/**/*
    - db/**/*.rb
    - node_modules/**/*
Layout/LineLength:
  IgnoredPatterns: ['\A\s*#']
Style/Documentation:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Bundler/OrderedGems:
  Enabled: false
Rails/SkipsModelValidations:
  Exclude:
    - app/services/imdb_importer.rb
    - app/services/imdb_importer/**/*.rb
Metrics/BlockLength:
  Exclude:
    - lib/tasks/**/*.rake
    - spec/**/*_spec.rb
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
Style/SymbolArray:
  Enabled: false
