require:
  - rubocop-rails

AllCops:
  NewCops: disable
  Exclude:
    - .git/**/*
    - bin/**/*
    - vendor/**/*
    - tmp/**/*
    - db/**/*.rb
Layout/LineLength:
  IgnoredPatterns: ['\A\s*#']
Style/Documentation:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Bundler/OrderedGems:
  Enabled: false
Rails/SkipsModelValidations:
  Exclude:
    - lib/parsers/**/*.rb
Metrics/BlockLength:
  Exclude:
    - lib/tasks/**/*.rake
